services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: chat-api
    environment:
      - TZ=UTC
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5190:80"
    networks:
      - chat-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - avatar-data:/app/Avatars:rw
      - sqlite-data:/app/Data:rw

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5190/chat-api}
        - REACT_APP_WS_URL=${REACT_APP_WS_URL:-http://localhost:5190/Hub}
        - REACT_APP_BASE_PATH=${REACT_APP_BASE_PATH:-}
    container_name: chat-client
    deploy:
      resources:
        limits:
          memory: 512M  # Reduced memory limit for 1GB server
        reservations:
          memory: 256M
    ports:
      - "8082:80"
    depends_on:
      - api
    networks:
      - chat-network
    environment:
      - TZ=UTC
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5190/chat-api}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL:-http://localhost:5190/Hub}
      - REACT_APP_BASE_PATH=${REACT_APP_BASE_PATH:-}

networks:
  chat-network:
    driver: bridge

volumes:
  avatar-data:
    driver: local
  sqlite-data:
    driver: local
