version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: DB/Dockerfile
    container_name: chat-db
    environment:
      - TZ=UTC
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_ENCRYPT=OPTIONAL
      - MSSQL_SSL_CERT_SKIP_VALIDATION=true
    ports:
      - "1433:1433"
    networks:
      - chat-network
    volumes:
      - mssql-data:/var/opt/mssql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -N -C || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: chat-api
    environment:
      - TZ=UTC
      - DB_SERVER=db,1433
      - DB_NAME=chat
      - DB_USERNAME=sa
      - DB_PASSWORD=${MSSQL_SA_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Docker
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5190:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - chat-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: |
        /bin/sh -c '
        /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" -N -C &&
        curl -f http://localhost:80/Hub/negotiate || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - avatar-data:/app/Avatars
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://api.zakharii.dev/projects/chat/chat-api
        - REACT_APP_WS_URL=https://api.zakharii.dev/projects/chat/Hub
    container_name: chat-client
    ports:
      - "8082:80"
    depends_on:
      - api
    networks:
      - chat-network
    environment:
      - TZ=UTC
      - REACT_APP_API_URL=https://api.zakharii.dev/projects/chat/chat-api
      - REACT_APP_WS_URL=https://api.zakharii.dev/projects/chat/Hub
      - REACT_APP_BASE_PATH=/projects/chat
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  chat-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local
  avatar-data:
    driver: local
