using API.Data;
using API.Models;
using API.Repos.ChatsRepo;
using API.Repos.MessagesRepo;
using API.Repos.UsersRepo;
using System.Text.RegularExpressions;

namespace API.Services
{
    public interface IGroupService
    {
        public Task<string?> RenameChatAsync(int chatId, string newName, AppUser currentUser);
        public Task<int?> CreateGroupChatAsync(NewChatModel chatModel, AppUser currentUser);
    }

    public class GroupService(ChatsRepo chatsRepo, MessagesRepo messagesRepo, UsersRepo usersRepo) : IGroupService
    {
        private static readonly Regex MyRegex = new Regex(@"^[a-zA-Z0-9. \-_]{4,20}$");
        public async Task<string?> RenameChatAsync(int chatId, string newName, AppUser currentUser)
        {
            if (!MyRegex.IsMatch(newName)) return null;
            var result = await chatsRepo.RenameChatAsync(chatId, newName);
            if (result == null) return null;
            return currentUser.UserName + " renamed chat to " + newName;
        }

        public async Task<int?> CreateGroupChatAsync(NewChatModel chatModel, AppUser currentUser)
        {
            //add creator to participants
            chatModel.ParticipantUserIds.Add(currentUser.Id);
            //make sure there are no duplicates
            var participants = chatModel.ParticipantUserIds.Distinct().ToList();
            //validate IDs
            foreach (var userId in participants)
            {
                var user = await usersRepo.GetUserByIdAsync(userId);

                if (user == null) return null;
            };

            var newChat = new Chat(chatModel.ChatName, true);

            await chatsRepo.CreateChatAsync(newChat);

            var members = participants.Select(userId => new ChatMember()
            {
                ChatId = newChat.ChatId,
                MemberId = userId,
                IsCreator = userId == currentUser.Id
            });

            foreach (var member in members) await chatsRepo.AddChatMemberAsync(member);

            var newMessage = new Message
            {
                ChatId = newChat.ChatId,
                Content = currentUser.UserName + " created chat.",
                RepliedTo = null,
                SenderId = currentUser.Id,
                IsAutogenerated = true
            };

            await messagesRepo.InsertAsync(newMessage);

            return newChat.ChatId;
        }
    }
}
