import { getSignalRConnection } from "./signalRConnection";
import { useEffect, useRef } from "react";
import { useAppDispatch, useAppSelector } from "../useAppSelectorAndDispatch";
import { prependChat, updateChat } from "../../redux/slices/chatsOverviewSlice";
import { prependMsg, updateMsg } from "../../redux/slices/currentChatSlice";
import { IMessage, ISystemMessage } from "../../Interfaces";
import { rmMemberByUname, addMember, rename } from "../../redux/slices/currentChatSlice";

const useWsMsgListener = () => {
  const connection = getSignalRConnection();
  const dispatch = useAppDispatch();
  const currentChatId = useAppSelector((state) => state.currentChat.chatId);
  const currentChatIdRef = useRef(currentChatId);

  useEffect(() => {
    currentChatIdRef.current = currentChatId;
  }, [currentChatId]);

  useEffect(() => {
    const handleNewMsg = (msg: IMessage) => {
      dispatch(prependChat(msg));
      if (msg.chatId === currentChatId) {
        dispatch(prependMsg(msg));
        
        // Handle system messages
        if (msg.isAutogenerated) {
          const systemMsg = msg as ISystemMessage;
          switch (systemMsg.type.toLowerCase()) {
            case 'rm_member':
              dispatch(rmMemberByUname(systemMsg.senderId));
              break;
            case 'add_member':
              dispatch(addMember(systemMsg.payload.member!));
              break;
            case 'rename_chat':
              dispatch(rename(systemMsg.payload.newChatName!));
              break;
          }
        }
      }
    };

    const handleMsgUpdate = (data: IMessage) => {
      dispatch(updateChat(data));
      if (data.chatId === currentChatId) {
        dispatch(updateMsg(data));
      }
    };

    connection.on("ReceiveNewMessage", handleNewMsg);
    connection.on("UpdateMessage", handleMsgUpdate);
    return () => {
      connection.off("ReceiveNewMessage", handleNewMsg);
      connection.off("UpdateMessage", handleMsgUpdate);
    };
  });
};

export default useWsMsgListener;
