export interface IUser {
  avatarName: string | null;
  bio: string | null;
  email: string | null;
  fullName: string | null;
  id: string | null;
  lastVisit: Date | null;
  userName: string | null;
  isOnline: boolean;
}

export interface IUsers {
  allUsers: IUser[];
  filteredUsers: IUser[];
  searchedUser: string | null;
}

export interface IChatMember {
  userName: string | null;
  memberId: string | null;
  isCreator: boolean
}

export interface IMessage {
  messageId: number;
  senderId: string;
  senderUserName: string;
  senderAvatarName: string | null;
  isAutogenerated: boolean;
  isDeleted: boolean;
  interlocutor: IUser | null;
  chatId: number;
  chatName: string | null;
  content: string;
  sentAt: string;
  likes: IUser[];
  seenBy: IUser[];
}

export interface IChats extends Array<IMessage> {}


export interface ICurrentChat {
  chatId: number | null;
  adminId: string | null;
  chatName: string | null;
  members: IUser[];
  messages: IMessage[];
  hasMoreMessages: boolean;
  isLoading: boolean;
}

export interface IChatsOverview {
  chats: IMessage[],
  hasMore: boolean,
  isLoading: boolean
}

export interface ICreateChat {
  name: string | null;
  candidates: IChatMember[];
}

export interface ILoginState {
  usernameOrEmail: string | null,
  password: string | null
}

export interface IregisterState {
  email: string | null;
  fullName: string | null;
  nickName: string | null;
  password: string | null;
  confirm: string | null;
}

export interface IMessageToSend {
  Content: string | null;
  RepliedTo: number | null;
}