using API.Data;
using API.Models;
using Microsoft.Extensions.FileSystemGlobbing.Internal;
using System.Text.RegularExpressions;

namespace API.Services.ChatsService
{
    public partial class ChatsService
    {
        [GeneratedRegex(@"^[a-zA-Z0-9. \-_]{4,20}$")]
        private static partial Regex MyRegex();
        public async Task<bool> RenameChatAsync(int chatId, string newName, AppUser currentUser)
        {
            Regex regex = MyRegex();
            if (!regex.IsMatch(newName)) return false;
            var member = await chatsRepo.GetChatMemberAsync(chatId, currentUser.Id);
            if (member == null) return false;
            var result = await chatsRepo.RenameChatAsync(chatId, newName);
            if (result == null) return false;

            var newMessage = new Message
            {
                ChatId = chatId,
                Content = currentUser.UserName + " renamed chat to " + newName,
                RepliedTo = null,
                SenderId = currentUser.Id!,
                IsAutogenerated = true
            };
            var inserted = await messagesRepo.InsertAsync(newMessage);
            if (inserted == null) return false;
            return true;
        }
    }
}
