using API.Data;
using API.Models;
using Microsoft.AspNetCore.Identity;

namespace API.Services.ChatsService
{
    public partial class ChatsService
    {
        public async Task<int?> CreateGroupChatAsync(NewChatModel chatModel, AppUser currentUser)
        {
            //add creator to participants
            chatModel.ParticipantUserIds.Add(currentUser.Id);
            //make sure there are no duplicates
            var participants = chatModel.ParticipantUserIds.Distinct().ToList();
            //validate IDs
            foreach (var userId in participants)
            {
                var user = await usersRepo.GetUserByIdAsync(userId);

                if (user == null) return null;
            };

            var newChat = new Chat
            {
                ChatName = chatModel.ChatName,
                IsGroupChat = true
            };

            await chatsRepo.CreateChatAsync(newChat);

            var members = participants.Select(userId => new ChatMember()
            {
                ChatId = newChat.ChatId,
                MemberId = userId,
                IsCreator = userId == currentUser.Id
            });

            foreach (var member in members) await chatsRepo.AddChatMemberAsync(member);

            var newMessage = new Message
            {
                ChatId = newChat.ChatId,
                Content = currentUser.UserName + " created chat.",
                RepliedTo = null,
                SenderId = currentUser.Id,
                IsAutogenerated = true
            };

            await messagesRepo.InsertAsync(newMessage);

            return newChat.ChatId;
        }
    }
}
